name: Build and deploy
on: push
    
permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build-and-deploy:

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/jekyll-build-pages@v1
        - uses: actions/setup-node@v4
          with:
              node-version: 18
        - run: npm install -g typescript
        - working-directory: ./_site
          run: tsc
        - uses: actions/upload-pages-artifact@v3
        #- uses: actions/deploy-pages@v4